/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/OR.glb -o ./src/components/Canvas/Gates/OrGate.jsx -T -E 
Files: ./models/OR.glb [3.54KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\OR-transformed.glb [1.55KB] (56%)
*/

import { useGLTF } from '@react-three/drei'

import { GATE_COLORS, PORT_COLORS } from '@/utils/colors'
import { IN_A, IN_B, OUT_Q } from '@/utils/constants'

export default function OrGate(props) {
  const { nodes, materials } = useGLTF('/OR-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['5'].geometry} material={materials.Khoi}>
        <meshStandardMaterial
          color={GATE_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
      <mesh position={[1.5, 0.125, 0]}>
        <boxGeometry args={[.4, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
      <mesh position={[-1.3, 0.125, .5]}>
        <boxGeometry args={[.6, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
      <mesh position={[-1.3, 0.125, -.5]}>
        <boxGeometry args={[.6, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
    </group>
  )
}

function NextState(wireState, gateState) {
  return {
    [IN_A]: wireState[IN_A],
    [IN_B]: wireState[IN_B],
    [OUT_Q]: wireState[IN_A] || wireState[IN_B]
  }
}

OrGate.NextState = NextState
OrGate.Init = function () { }

useGLTF.preload('/OR-transformed.glb')
