/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\AND.glb --transform 
Files: .\public\models\AND.glb [8.99KB] > C:\Users\ducmi\projects\logic-gate-simulators\AND-transformed.glb [2.08KB] (77%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('models/AND-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes['2'].geometry}
        material={nodes['2'].material}
        position={[-1.027, 0.045, -0.05]} />

    </group>
  )
}

useGLTF.preload('/AND-transformed.glb')
