/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\AND_GATE.glb --transform 
Files: .\public\models\AND_GATE.glb [2.78KB] > C:\Users\ducmi\projects\logic-gate-simulators\AND_GATE-transformed.glb [1.57KB] (44%)
*/

import { useGLTF } from '@react-three/drei'

export function AndGate(props) {
  const { nodes, materials } = useGLTF('models/AND_GATE-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['4'].geometry} material={nodes['4'].material}
        scale={0.25} position={[0.01, 0, 0]}>

        <meshNormalMaterial />
      </mesh>
    </group>
  )
}

useGLTF.preload('/AND_GATE-transformed.glb')
