/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\models\NAND_GATE.glb --transform 
Files: .\models\NAND_GATE.glb [76.16KB] > C:\Users\ducmi\projects\logic-gate-simulators\NAND_GATE-transformed.glb [13.14KB] (83%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshNormalMaterial, MeshStandardMaterial } from 'three'

export function NandGate(props) {
  const { nodes, materials } = useGLTF('models/NAND_GATE-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['3'].geometry} material={nodes['3'].material}
        scale={0.25} position={[-0.006, 0.07, 0]}>
        <meshStandardMaterial />
      </mesh>
    </group>
  )
}

useGLTF.preload('/NAND_GATE-transformed.glb')
