/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\models\OR_GATE.glb --transform 
Files: .\models\OR_GATE.glb [3.39KB] > C:\Users\ducmi\projects\logic-gate-simulators\OR_GATE-transformed.glb [1.62KB] (52%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function OrGate(props) {
  const { nodes, materials } = useGLTF('models/OR_GATE-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['5'].geometry} material={nodes['5'].material}
        scale={0.25} position={[-0.006, 0, 0]}>
        <meshNormalMaterial />
      </mesh>
    </group>
  )
}

useGLTF.preload('/OR_GATE-transformed.glb')
