/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\NOT_GATE.glb --transform 
Files: .\public\models\NOT_GATE.glb [3.78KB] > C:\Users\ducmi\projects\logic-gate-simulators\NOT_GATE-transformed.glb [1.77KB] (53%)
*/

import { useGLTF } from '@react-three/drei'

export function NotGate(props) {
  const { nodes, materials } = useGLTF('models/NOT-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['1'].geometry} material={nodes['1'].material}
        scale={0.25} position={[-0.005, 0.025, 0]}>
        <meshNormalMaterial />
      </mesh>
    </group>
  )
}

useGLTF.preload('/NOT_GATE-transformed.glb')
