/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/AND.glb -o ./src/components/Canvas/Gates/AndGate.jsx -T -E 
Files: ./models/AND.glb [27.98KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\AND-transformed.glb [5.4KB] (81%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GATE_COLORS, PORT_COLORS } from '@/utils/colors'


export default function AndGate(props) {
  const { nodes, materials } = useGLTF('/AND-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['4'].geometry}>
        <meshStandardMaterial
          color={GATE_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
      <mesh position={[1.5, 0.125, 0]}>
        <boxGeometry args={[.4, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
      <mesh position={[-1.5, 0.125, .5]}>
        <boxGeometry args={[.4, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
      <mesh position={[-1.5, 0.125, -.5]}>
        <boxGeometry args={[.4, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
    </group>
  )
}

const gateState = { in_A: 0, in_B: 0, out_Q: 0 }
const wireState = { in_A: 0, in_B: 0, out_Q: 0 }
function NextState(wireState, gateState) {
  return {
    in_A: wireState.in_A,
    in_B: wireState.in_B,
    out_Q: wireState.in_A && wireState.in_B
  }
}

function GetPort(port, gatePos) {
  switch (port) {
    case 'in_A':
      break;
    case 'in_B':
      break;
    case 'out_Q':
      break;
    default:
      return null
  }
}
AndGate.inputs = ['in_A', 'in_B']
AndGate.outputs = ['out_Q']
AndGate.defaultState = { in_A: 0, in_B: 0, out_Q: 0 }
AndGate.GetPort = GetPort
AndGate.NextState = NextState

useGLTF.preload('/AND-transformed.glb')
