/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/NOR.glb -o ./src/components/Canvas/Gates/NorGate.jsx -T -E 
Files: ./models/NOR.glb [28.94KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\NOR-transformed.glb [5.49KB] (81%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

import { GATE_COLORS, PORT_COLORS } from '@/utils/colors'

export default function NorGate(props) {
  const { nodes, materials } = useGLTF('/NOR-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['3'].geometry} material={materials.Khoi}>
        <meshStandardMaterial
          color={GATE_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
      <mesh geometry={nodes.Cot3.geometry} material={nodes.Cot3.material}>
        <meshStandardMaterial
          color={GATE_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
      <mesh position={[-1.3, 0.125, .5]}>
        <boxGeometry args={[.6, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
      <mesh position={[-1.3, 0.125, -.5]}>
        <boxGeometry args={[.6, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
    </group>
  )
}

const gateState = { in_A: 0, in_B: 0, out_Q: 0 }
const wireState = { in_A: 0, in_B: 0, out_Q: 0 }
function NextState(wireState, gateState) {
  let result = wireState.in_A || wireState.in_B
  return {
    in_A: wireState.in_A,
    in_B: wireState.in_B,
    out_Q: !result
  }
}

NorGate.inputs = ['in_A', 'in_B']
NorGate.outputs = ['out_Q']
NorGate.defaultState = { in_A: 0, in_B: 0, out_Q: 0 }
NorGate.NextState = NextState

useGLTF.preload('/NOR-transformed.glb')
