/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/NAND.glb -o ./public/NandGate.jsx -T -E 
Files: ./models/NAND.glb [8.55KB] > C:\Users\ducmi\projects\logic-gate-simulators\public\NAND-transformed.glb [2.94KB] (66%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function NandGate(props) {
  const { nodes, materials } = useGLTF('/NAND-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['2'].geometry} material={materials.Khoi} />
      <mesh geometry={nodes.Cot2.geometry} material={nodes.Cot2.material} />
    </group>
  )
}

useGLTF.preload('/NAND-transformed.glb')
