/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/NOT.glb -o ./public/NotGate.jsx -T -E 
Files: ./models/NOT.glb [7.34KB] > C:\Users\ducmi\projects\logic-gate-simulators\public\NOT-transformed.glb [2.73KB] (63%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function NotGate(props) {
  const { nodes, materials } = useGLTF('/NOT-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['1'].geometry} material={materials.Khoi} />
      <mesh geometry={nodes.Cot1.geometry} material={nodes.Cot1.material} />
    </group>
  )
}

useGLTF.preload('/NOT-transformed.glb')
