/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/XOR.glb -o ./public/XorGate.jsx -T -E 
Files: ./models/XOR.glb [6.96KB] > C:\Users\ducmi\projects\logic-gate-simulators\01_client\public\XOR-transformed.glb [1.96KB] (72%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function XorGate(props) {
  const { nodes, materials } = useGLTF('/XOR-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['6'].geometry} material={materials.Khoi} />
    </group>
  )
}

useGLTF.preload('/XOR-transformed.glb')
