/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/AND.glb -o ./public/AndGate.jsx -T -E 
Files: ./models/AND.glb [2.81KB] > C:\Users\ducmi\projects\logic-gate-simulators\01.client\public\AND-transformed.glb [1.36KB] (52%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function AndGate(props) {
  const { nodes, materials } = useGLTF('/AND-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['4'].geometry} material={materials.Khoi} />
    </group>
  )
}

useGLTF.preload('/AND-transformed.glb')
