/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/NOR.glb -o ./public/NorGate.jsx -T -E 
Files: ./models/NOR.glb [8.14KB] > C:\Users\ducmi\vsc\aaaa\01_client\public\NOR-transformed.glb [2.92KB] (64%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function NorGate(props) {
  const { nodes, materials } = useGLTF('/NOR-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['3'].geometry} material={materials.Khoi} />
      <mesh geometry={nodes.Cot3.geometry} material={nodes.Cot3.material} />
    </group>
  )
}

useGLTF.preload('/NOR-transformed.glb')
