/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/AND.glb -o ./src/components/Canvas/Gates/AndGate.jsx -T -E 
Files: ./models/AND.glb [27.98KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\AND-transformed.glb [5.4KB] (81%)
*/

import { useGLTF } from '@react-three/drei'

import { GATE_COLORS, PORT_COLORS } from '@/utils/colors'
import { AND_GATE, IN_A, IN_B, INPUT_PIN, INVALID_PIN, OUT_Q, OUTPUT_PIN } from '@/utils/constants'
import GateName from './GateName'
import NotIndicator from './NotIndicator'

export default function AndGate({ name, outputs, inputs, ...props }) {
  const { nodes, materials } = useGLTF('/AND-transformed.glb')
  const outQ = !outputs?.[OUT_Q]?.isNeg
  const inA = !inputs?.[IN_A]?.isNeg
  const inB = !inputs?.[IN_B]?.isNeg
  return (
    <group {...props} dispose={null}>
      <GateName name={name} />
      <mesh geometry={nodes['1'].geometry} material={materials}>
        <meshStandardMaterial
          color={GATE_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
      <mesh position={[.8, 1, 0]}>
        <boxGeometry args={[.4, .4, .4]} />
        <meshStandardMaterial
          color={outputs?.[OUT_Q]?.status ? 0xff0000 : 0x0000ff}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
      {outQ
        ? <mesh position={[1.5, 0.125, 0]}>
          <boxGeometry args={[.4, .3, .3]} />
          <meshStandardMaterial
            color={PORT_COLORS}
            metalness={1}
            roughness={0.4}
            envMapIntensity={1.5}
            flatShading={true} />
        </mesh>
        : <NotIndicator position={[1.75, 0.125, 0]} />}
      {inA
        ? <mesh position={[-1.5, 0.125, -.5]}>
          <boxGeometry args={[.4, .3, .3]} />
          <meshStandardMaterial
            color={PORT_COLORS}
            metalness={1}
            roughness={0.4}
            envMapIntensity={1.5}
            flatShading={true} />
        </mesh>
        : <NotIndicator position={[-1.75, 0.125, -.5]} />}
      {inB
        ? <mesh position={[-1.5, 0.125, .5]}>
          <boxGeometry args={[.4, .3, .3]} />
          <meshStandardMaterial
            color={PORT_COLORS}
            metalness={1}
            roughness={0.4}
            envMapIntensity={1.5}
            flatShading={true} />
        </mesh>
        : <NotIndicator position={[-1.75, 0.125, .5]} />}
    </group>
  )
}
AndGate.gate_name = AND_GATE
AndGate.delay = 1
AndGate.size_length = 1
AndGate.defaultInputs = [IN_A, IN_B]
AndGate.defaultOutputs = [OUT_Q]
AndGate.CheckPinType = (pin) => {
  if (pin === IN_A || pin === IN_B) return INPUT_PIN
  if (pin === OUT_Q) return OUTPUT_PIN
  return INVALID_PIN
}
AndGate.NextStep = (wireState = {}) => {
  return { [OUT_Q]: wireState[IN_A] && wireState[IN_B] }
}
AndGate.GetPinPositions = function (x, y, z) {
  return {
    [IN_A]: [
      [x * 5 + 0.5, 0, z * 5 + 2],
      [x * 5 + 1, 0, z * 5 + 2],
    ],
    [IN_B]: [
      [x * 5 + 0.5, y, z * 5 + 3],
      [x * 5 + 1, y, z * 5 + 3],
    ],
    [OUT_Q]: [
      [x * 5 + 4, y, z * 5 + 2.5],
      [x * 5 + 4.75, y, z * 5 + 2.5],
    ]
  }
}
AndGate.GetSelectPin = function (contactPoint, gateWorldPos, gatePos) {
  const pinPos = AndGate.GetPinPositions(gatePos.x, gatePos.y, gatePos.z)
  if (contactPoint.x > gateWorldPos.x) {
    return {
      pin: OUT_Q,
      position: pinPos[OUT_Q][1]
    }
  } else {
    if (contactPoint.z < gateWorldPos.z) {
      return {
        pin: IN_A,
        position: pinPos[IN_A][0]
      }
    } else {
      return {
        pin: IN_B,
        position: pinPos[IN_B][0]
      }
    }
  }
}
useGLTF.preload('/AND-transformed.glb')
