/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/AND.glb -o ./src/components/Canvas/Gates/AndGate.jsx -T -E 
Files: ./models/AND.glb [27.98KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\AND-transformed.glb [5.4KB] (81%)
*/

import { useGLTF } from '@react-three/drei'

import { GATE_COLORS, PORT_COLORS } from '@/utils/colors'
import { AND_GATE, IN_A, IN_B, INPUT_PIN, INVALID_PIN, OUT_Q, OUTPUT_PIN } from '@/utils/constants'
import GateName from './GateName'

export default function AndGate({ name, state, ...props }) {
  const { nodes, materials } = useGLTF('/AND-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <GateName name={name} />
      <mesh geometry={nodes['4'].geometry} material={materials}>
        <meshStandardMaterial
          color={GATE_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
      <mesh position={[1.5, 0.125, 0]}>
        <boxGeometry args={[.4, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
      <mesh position={[.8, 1, 0]}>
        <boxGeometry args={[.4, .4, .4]} />
        <meshStandardMaterial
          color={state?.[OUT_Q].status ? 0xff0000 : 0x0000ff}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
      <mesh position={[-1.5, 0.125, .5]}>
        <boxGeometry args={[.4, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
      <mesh position={[-1.5, 0.125, -.5]}>
        <boxGeometry args={[.4, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
    </group>
  )
}
AndGate.gate_name = AND_GATE
AndGate.delay = 3
AndGate.defaultInputs = JSON.stringify({
  [IN_A]: { srcGate: "", srcPin: "", selfGate: "", selfPin: "" },
  [IN_B]: { srcGate: "", srcPin: "", selfGate: "", selfPin: "" }
})
AndGate.defaultOutputs = JSON.stringify({
  [OUT_Q]: { status: false, destGate: [] }
})
AndGate.CheckPinType = (pin) => {
  if (pin === IN_A || pin === IN_B) return INPUT_PIN
  if (pin === OUT_Q) return OUTPUT_PIN
  return INVALID_PIN
}
AndGate.NextStep = (wireState = {}) => {
  return { [OUT_Q]: wireState[IN_A] && wireState[IN_B] }
}

useGLTF.preload('/AND-transformed.glb')
