/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/NAND.glb -o ./src/components/Canvas/Gates/NandGate.jsx -T -E 
Files: ./models/NAND.glb [48.19KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\NAND-transformed.glb [8.25KB] (83%)
*/

import { GATE_COLORS, PORT_COLORS } from '@/utils/colors'
import { IN_A, IN_B, OUT_Q } from '@/utils/constants'
import { useGLTF } from '@react-three/drei'

export default function NandGate(props) {
  const { nodes, materials } = useGLTF('/NAND-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['2'].geometry} material={materials.Khoi}>
        <meshStandardMaterial
          color={GATE_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
      <mesh geometry={nodes.Cot2.geometry} material={nodes.Cot2.material}>
        <meshStandardMaterial
          color={GATE_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
      <mesh position={[-1.5, 0.125, .5]}>
        <boxGeometry args={[.4, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
      <mesh position={[-1.5, 0.125, -.5]}>
        <boxGeometry args={[.4, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
    </group>
  )
}

const gateState = { [IN_A]: 0, [IN_B]: 0, [OUT_Q]: 0 }
const wireState = { [IN_A]: 0, [IN_B]: 0, [OUT_Q]: 0 }
function NextState(wireState, gateState) {
  return {
    [IN_A]: wireState[IN_A],
    [IN_B]: wireState[IN_B],
    [OUT_Q]: !(wireState[IN_A] && wireState[IN_B])
  }
}

NandGate.inputs = [IN_A, IN_B]
NandGate.outputs = [OUT_Q]
NandGate.defaultState = { [IN_A]: 0, [IN_B]: 0, [OUT_Q]: 0 }
NandGate.NextState = NextState

useGLTF.preload('/NAND-transformed.glb')
