/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/NAND.glb -o ./src/components/Canvas/Gates/NandGate.jsx -T -E 
Files: ./models/NAND.glb [48.19KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\NAND-transformed.glb [8.25KB] (83%)
*/

import { GATE_COLORS, PORT_COLORS } from '@/utils/colors'
import { DEFAULT_STATE_A, IN_A, IN_B, OUT_Q } from '@/utils/constants'
import { Billboard, Float, Text, useGLTF } from '@react-three/drei'
import GateName from './GateName'

export default function NandGate({ name, ...props }) {
  const { nodes, materials } = useGLTF('/NAND-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <GateName name={name} />
      <mesh geometry={nodes['2'].geometry} material={materials.Khoi}>
        <meshStandardMaterial
          color={GATE_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
      <mesh geometry={nodes.Cot2.geometry} material={nodes.Cot2.material}>
        <meshStandardMaterial
          color={GATE_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
      <mesh position={[-1.5, 0.125, .5]}>
        <boxGeometry args={[.4, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
      <mesh position={[-1.5, 0.125, -.5]}>
        <boxGeometry args={[.4, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
    </group>
  )
}

function NextState(wireState) {
  return {
    [IN_A]: wireState[IN_A],
    [IN_B]: wireState[IN_B],
    [OUT_Q]: !(wireState[IN_A] && wireState[IN_B])
  }
}

NandGate.NextState = NextState
NandGate.Init = function () { }

useGLTF.preload('/NAND-transformed.glb')
