/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/NOR.glb -o ./src/components/Canvas/Gates/NorGate.jsx -T -E 
Files: ./models/NOR.glb [28.94KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\NOR-transformed.glb [5.49KB] (81%)
*/

import { useGLTF } from '@react-three/drei'

import { GATE_COLORS, PORT_COLORS } from '@/utils/colors'
import { DEFAULT_STATE_A, IN_A, IN_B, OUT_Q } from '@/utils/constants'

export default function NorGate(props) {
  const { nodes, materials } = useGLTF('/NOR-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['3'].geometry} material={materials.Khoi}>
        <meshStandardMaterial
          color={GATE_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
      <mesh geometry={nodes.Cot3.geometry} material={nodes.Cot3.material}>
        <meshStandardMaterial
          color={GATE_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
      <mesh position={[-1.3, 0.125, .5]}>
        <boxGeometry args={[.6, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
      <mesh position={[-1.3, 0.125, -.5]}>
        <boxGeometry args={[.6, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
    </group>
  )
}

function NextState(wireState) {
  return {
    [IN_A]: wireState[IN_A],
    [IN_B]: wireState[IN_B],
    [OUT_Q]: !(wireState[IN_A] || wireState[IN_B])
  }
}

NorGate.NextState = NextState
NorGate.Init = function () { }

useGLTF.preload('/NOR-transformed.glb')
