/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/NOR.glb -o ./src/components/Canvas/Gates/NorGate.jsx -T -E 
Files: ./models/NOR.glb [28.94KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\NOR-transformed.glb [5.49KB] (81%)
*/

import { useGLTF } from '@react-three/drei'

import { GATE_COLORS, PORT_COLORS } from '@/utils/colors'
import { IN_A, IN_B, INPUT_PIN, INVALID_PIN, NOR_GATE, OUT_Q, OUTPUT_PIN } from '@/utils/constants'
import GateName from './GateName'

export default function NorGate({ name, state, ...props }) {
  const { nodes, materials } = useGLTF('/NOR-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <GateName name={name} />
      <mesh geometry={nodes['3'].geometry} material={materials.Khoi}>
        <meshStandardMaterial
          color={GATE_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
      <mesh geometry={nodes.Cot3.geometry} material={nodes.Cot3.material}>
        <meshStandardMaterial
          color={GATE_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
      <mesh position={[.8, 1, 0]}>
        <boxGeometry args={[.4, .4, .4]} />
        <meshStandardMaterial
          color={state?.[OUT_Q].status ? 0xff0000 : 0x0000ff}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
      <mesh position={[-1.3, 0.125, .5]}>
        <boxGeometry args={[.6, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
      <mesh position={[-1.3, 0.125, -.5]}>
        <boxGeometry args={[.6, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
    </group>
  )
}
NorGate.gate_name = NOR_GATE
NorGate.delay = 2
NorGate.defaultInputs = JSON.stringify({
  [IN_A]: { srcGate: "", srcPin: "", selfGate: "", selfPin: "" },
  [IN_B]: { srcGate: "", srcPin: "", selfGate: "", selfPin: "" }
})
NorGate.defaultOutputs = JSON.stringify({
  [OUT_Q]: { status: true, destGate: [] }
})
NorGate.CheckPinType = (pin) => {
  if (pin === IN_A || pin === IN_B) return INPUT_PIN
  if (pin === OUT_Q) return OUTPUT_PIN
  return INVALID_PIN
}
NorGate.NextStep = (wireState = {}) => {
  return { [OUT_Q]: !(wireState[IN_A] || wireState[IN_B]) }
}
useGLTF.preload('/NOR-transformed.glb')
