/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/NOT.glb -o ./src/components/Canvas/Gates/NotGate.jsx -T -E 
Files: ./models/NOT.glb [26.64KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\NOT-transformed.glb [5.07KB] (81%)
*/

import { useGLTF } from '@react-three/drei'

import { GATE_COLORS, PORT_COLORS } from '@/utils/colors'
import { IN_A, OUT_Q } from '@/utils/constants'

export default function NotGate(props) {
  const { nodes, materials } = useGLTF('/NOT-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['1'].geometry} material={materials.Khoi}>
        <meshStandardMaterial
          color={GATE_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
      <mesh geometry={nodes.Cot1.geometry} material={nodes.Cot1.material}>
        <meshStandardMaterial
          color={GATE_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
      <mesh position={[-1.5, 0.125, 0]}>
        <boxGeometry args={[.4, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
    </group>
  )
}

const gateState = { [IN_A]: 0, [OUT_Q]: 0 }
const wireState = { [IN_A]: 0, [OUT_Q]: 0 }
function NextState(wireState, gateState) {
  return {
    [IN_A]: wireState[IN_A],
    [OUT_Q]: !wireState[IN_A]
  }
}

NotGate.inputs = [IN_A]
NotGate.outputs = [OUT_Q]
NotGate.defaultState = { [IN_A]: false, [OUT_Q]: false }
NotGate.NextState = NextState

useGLTF.preload('/NOT-transformed.glb')
