/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/NOT.glb -o ./src/components/Canvas/Gates/NotGate.jsx -T -E 
Files: ./models/NOT.glb [26.64KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\NOT-transformed.glb [5.07KB] (81%)
*/

import { useGLTF } from '@react-three/drei'

import { GATE_COLORS, PORT_COLORS } from '@/utils/colors'
import { IN_A, INPUT_PIN, INVALID_PIN, NOT_GATE, OUT_Q, OUTPUT_PIN } from '@/utils/constants'
import GateName from './GateName'

export default function NotGate({ name, state, ...props }) {
  const { nodes, materials } = useGLTF('/NOT-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <GateName name={name} />
      <mesh geometry={nodes['1'].geometry} material={materials.Khoi}>
        <meshStandardMaterial
          color={GATE_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
      <mesh position={[.8, 1, 0]}>
        <boxGeometry args={[.4, .4, .4]} />
        <meshStandardMaterial
          color={state?.[OUT_Q]?.status ? 0xff0000 : 0x0000ff}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
      <mesh geometry={nodes.Cot1.geometry} material={nodes.Cot1.material}>
        <meshStandardMaterial
          color={GATE_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
      <mesh position={[-1.5, 0.125, 0]}>
        <boxGeometry args={[.4, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
    </group>
  )
}
NotGate.gate_name = NOT_GATE
NotGate.delay = 1
NotGate.defaultInputs = JSON.stringify({
  [IN_A]: { srcGate: "", srcPin: "", selfGate: "", selfPin: "" }
})
NotGate.defaultOutputs = JSON.stringify({
  [OUT_Q]: { status: true, destGate: [] }
})
NotGate.CheckPinType = (pin) => {
  if (pin === IN_A) return INPUT_PIN
  if (pin === OUT_Q) return OUTPUT_PIN
  return INVALID_PIN
}
NotGate.NextStep = (wireState = {}) => {
  return { [OUT_Q]: !wireState[IN_A] }
}

useGLTF.preload('/NOT-transformed.glb')
