/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/XOR.glb -o ./src/components/Canvas/Gates/XorGate.jsx -T -E 
Files: ./models/XOR.glb [7KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\XOR-transformed.glb [1.98KB] (72%)
*/

import { useGLTF } from '@react-three/drei'

import { GATE_COLORS, PORT_COLORS } from '@/utils/colors'
import { IN_A, IN_B, OUT_Q } from '@/utils/constants'
import GateName from './GateName'

export default function XorGate({ name, ...props }) {
  const { nodes, materials } = useGLTF('/XOR-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <GateName name={name} />
      <mesh geometry={nodes['6'].geometry} material={materials.Khoi}>
        <meshStandardMaterial
          color={GATE_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
      <mesh position={[1.5, 0.125, 0]}>
        <boxGeometry args={[.4, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
      <mesh position={[-1.4, 0.125, .5]}>
        <boxGeometry args={[.5, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
      <mesh position={[-1.4, 0.125, -.5]}>
        <boxGeometry args={[.5, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
    </group>
  )
}

function NextState(wireState) {
  return {
    [IN_A]: wireState[IN_A],
    [IN_B]: wireState[IN_B],
    [OUT_Q]: wireState[IN_A] != wireState[IN_B]
  }
}

XorGate.NextState = NextState
XorGate.Init = function () {
}

useGLTF.preload('/XOR-transformed.glb')
