/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/XOR.glb -o ./src/components/Canvas/Gates/XorGate.jsx -T -E 
Files: ./models/XOR.glb [7KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\XOR-transformed.glb [1.98KB] (72%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

import { GATE_COLORS, PORT_COLORS } from '@/utils/colors'
import { IN_A, IN_B, OUT_Q } from '@/utils/constants'

export default function XorGate(props) {
  const { nodes, materials } = useGLTF('/XOR-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['6'].geometry} material={materials.Khoi}>
        <meshStandardMaterial
          color={GATE_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
      <mesh position={[1.5, 0.125, 0]}>
        <boxGeometry args={[.4, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
      <mesh position={[-1.4, 0.125, .5]}>
        <boxGeometry args={[.5, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
      <mesh position={[-1.4, 0.125, -.5]}>
        <boxGeometry args={[.5, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
    </group>
  )
}

const gateState = { [IN_A]: 0, [IN_B]: 0, [OUT_Q]: 0 }
const wireState = { [IN_A]: 0, [IN_B]: 0, [OUT_Q]: 0 }
function NextState(wireState, gateState) {
  return {
    [IN_A]: wireState[IN_A],
    [IN_B]: wireState[IN_B],
    [OUT_Q]: wireState[IN_A] != wireState[IN_B]
  }
}

XorGate.inputs = [IN_A, IN_B]
XorGate.outputs = [OUT_Q]
XorGate.defaultState = { [IN_A]: 0, [IN_B]: 0, [OUT_Q]: 0 }
XorGate.NextState = NextState

useGLTF.preload('/XOR-transformed.glb')
