/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/AND.glb -o ./src/components/Canvas/Gates/AndGate.jsx -T -E 
Files: ./models/AND.glb [27.98KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\AND-transformed.glb [5.4KB] (81%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function AndGate(props) {
  const { nodes, materials } = useGLTF('/AND-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['4'].geometry} material={materials.Khoi}>
        <meshNormalMaterial />
      </mesh>
    </group>
  )
}

useGLTF.preload('/AND-transformed.glb')
