/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/NAND.glb -o ./src/components/Canvas/Gates/NandGate.jsx -T -E 
Files: ./models/NAND.glb [48.19KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\NAND-transformed.glb [8.25KB] (83%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function NandGate(props) {
  const { nodes, materials } = useGLTF('/NAND-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['1'].geometry} material={materials.Khoi} />
      <mesh geometry={nodes.Cot1.geometry} material={materials.Den} />
    </group>
  )
}

useGLTF.preload('/NAND-transformed.glb')
