/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/NAND.glb -o ./src/components/Canvas/Gates/NandGate.jsx -T -E 
Files: ./models/NAND.glb [48.19KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\NAND-transformed.glb [8.25KB] (83%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function NandGate(props) {
  const { nodes, materials } = useGLTF('/NAND-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['2'].geometry} material={materials.Khoi}>
        <meshNormalMaterial />
      </mesh>
      <mesh geometry={nodes.Cot2.geometry} material={nodes.Cot2.material}>
        <meshNormalMaterial />
      </mesh>
    </group>
  )
}

const gateState = { in_A: 0, in_B: 0, out_Q: 0 }
const wireState = { in_A: 0, in_B: 0, out_Q: 0 }
function NextState(wireState, gateState) {
  let result = wireState.in_A && wireState.in_B
  return {
    in_A: wireState.in_A,
    in_B: wireState.in_B,
    out_Q: !result
  }
}

NandGate.inputs = ['in_A', 'in_B']
NandGate.outputs = ['out_Q']
NandGate.NextState = NextState

useGLTF.preload('/NAND-transformed.glb')
