/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/NOR.glb -o ./src/components/Canvas/Gates/NorGate.jsx -T -E 
Files: ./models/NOR.glb [28.94KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\NOR-transformed.glb [5.49KB] (81%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function NorGate(props) {
  const { nodes, materials } = useGLTF('/NOR-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['3'].geometry} material={materials.Khoi} />
      <mesh geometry={nodes.Cot3.geometry} material={materials.Den} />
    </group>
  )
}

useGLTF.preload('/NOR-transformed.glb')
