/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/NOT.glb -o ./src/components/Canvas/Gates/NotGate.jsx -T -E 
Files: ./models/NOT.glb [26.64KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\NOT-transformed.glb [5.07KB] (81%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function NotGate(props) {
  const { nodes, materials } = useGLTF('/NOT-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['1'].geometry} material={materials.Khoi}>
        <meshStandardMaterial
          color="#f0f0f0"
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
      <mesh geometry={nodes.Cot1.geometry} material={nodes.Cot1.material}>
        <meshStandardMaterial
          color="#f0f0f0"
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
    </group>
  )
}

NotGate.inputs = ['in_A']
NotGate.outputs = ['out_Q']

const gateState = { in_A: 0, out_Q: 0 }
const wireState = { in_A: 0, out_Q: 0 }
NotGate.NextState = function (wireState, gateState) {
  return {
    in_A: wireState.in_A,
    out_Q: !wireState.in_A
  }
}

useGLTF.preload('/NOT-transformed.glb')
