/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/NOT.glb -o ./src/components/Canvas/Gates/NotGate.jsx -T -E 
Files: ./models/NOT.glb [26.64KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\NOT-transformed.glb [5.07KB] (81%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function NotGate(props) {
  const { nodes, materials } = useGLTF('/NOT-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['1'].geometry} material={materials.Khoi}>
        <meshNormalMaterial />
      </mesh>
      <mesh geometry={nodes.Cot1.geometry} material={nodes.Cot1.material}>
        <meshNormalMaterial />
      </mesh>
    </group>
  )
}

useGLTF.preload('/NOT-transformed.glb')
