/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/OR.glb -o ./src/components/Canvas/Gates/OrGate.jsx -T -E 
Files: ./models/OR.glb [3.54KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\OR-transformed.glb [1.55KB] (56%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function OrGate(props) {
  const { nodes, materials } = useGLTF('/OR-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['5'].geometry} material={materials.Khoi}>
        <meshNormalMaterial />
      </mesh>
    </group>
  )
}

const gateState = { in_A: 0, in_B: 0, out_Q: 0 }
const wireState = { in_A: 0, in_B: 0, out_Q: 0 }
function NextState(wireState, gateState) {
  let result = wireState.in_A || wireState.in_B
  if (result === gateState.result) return { needUpdate: false }

  return {
    state: { in_A: wireState.in_A, in_B: wireState.in_B, out_Q: result },
    needUpdate: true
  }
}

OrGate.inputs = ['in_A', 'in_B']
OrGate.outputs = ['out_Q']
OrGate.NextState = NextState

useGLTF.preload('/OR-transformed.glb')
