/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/OR.glb -o ./src/components/Canvas/Gates/OrGate.jsx -T -E 
Files: ./models/OR.glb [3.54KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\OR-transformed.glb [1.55KB] (56%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function OrGate(props) {
  const { nodes, materials } = useGLTF('/OR-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['5'].geometry} material={materials.Khoi} />
    </group>
  )
}

useGLTF.preload('/OR-transformed.glb')
