/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/XOR.glb -o ./src/components/Canvas/Gates/XorGate.jsx -T -E 
Files: ./models/XOR.glb [7KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\XOR-transformed.glb [1.98KB] (72%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function XorGate(props) {
  const { nodes, materials } = useGLTF('/XOR-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['6'].geometry} material={materials.Khoi}>
        <meshNormalMaterial />
      </mesh>
    </group>
  )
}

useGLTF.preload('/XOR-transformed.glb')
