/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/XOR.glb -o ./src/components/Canvas/Gates/XorGate.jsx -T -E 
Files: ./models/XOR.glb [7KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\XOR-transformed.glb [1.98KB] (72%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function XorGate(props) {
  const { nodes, materials } = useGLTF('/XOR-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['6'].geometry} material={materials.Khoi}>
        <meshNormalMaterial />
      </mesh>
    </group>
  )
}

const gateState = { in_A: 0, in_B: 0, out_Q: 0 }
const wireState = { in_A: 0, in_B: 0, out_Q: 0 }
function NextState(wireState, gateState) {
  return {
    in_A: wireState.in_A,
    in_B: wireState.in_B,
    out_Q: wireState.in_A == wireState.in_B
  }
}

XorGate.inputs = ['in_A', 'in_B']
XorGate.outputs = ['out_Q']
XorGate.NextState = NextState

useGLTF.preload('/XOR-transformed.glb')
