/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/OR.glb -o ./src/components/Canvas/Gates/OrGate.jsx -T -E 
Files: ./models/OR.glb [3.54KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\OR-transformed.glb [1.55KB] (56%)
*/

import { useGLTF } from '@react-three/drei'

import { GATE_COLORS, PORT_COLORS } from '@/utils/colors'
import { IN_A, IN_B, INPUT_PIN, INVALID_PIN, OR_GATE, OUT_Q, OUTPUT_PIN } from '@/utils/constants'
import GateName from './GateName'
import NotIndicator from './NotIndicator'

export default function OrGate({ name, outputs, inputs, ...props }) {
  const { nodes, materials } = useGLTF('/OR-transformed.glb')
  const outQ = !outputs?.[OUT_Q]?.isNeg
  const inA = !inputs?.[IN_A]?.isNeg
  const inB = !inputs?.[IN_B]?.isNeg
  return (
    <group {...props} dispose={null}>
      <GateName name={name} />
      <mesh geometry={nodes['3'].geometry} material={materials.Khoi}>
        <meshStandardMaterial
          color={GATE_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
      <mesh position={[.8, 1, 0]}>
        <boxGeometry args={[.4, .4, .4]} />
        <meshStandardMaterial
          color={outputs?.[OUT_Q]?.status ? 0xff0000 : 0x0000ff}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
      {outQ
        ? <mesh position={[1.5, 0.125, 0]}>
          <boxGeometry args={[.4, .3, .3]} />
          <meshStandardMaterial
            color={PORT_COLORS}
            metalness={1}
            roughness={0.4}
            envMapIntensity={1.5}
            flatShading={true} />
        </mesh>
        : <NotIndicator position={[1.75, 0.125, 0]} />}
      {inA
        ? <mesh position={[-1.5, 0.125, -.5]}>
          <boxGeometry args={[.4, .3, .3]} />
          <meshStandardMaterial
            color={PORT_COLORS}
            metalness={1}
            roughness={0.4}
            envMapIntensity={1.5}
            flatShading={true} />
        </mesh>
        : <NotIndicator position={[-1.6, 0.125, -.5]} />}
      {inB
        ? <mesh position={[-1.5, 0.125, .5]}>
          <boxGeometry args={[.4, .3, .3]} />
          <meshStandardMaterial
            color={PORT_COLORS}
            metalness={1}
            roughness={0.4}
            envMapIntensity={1.5}
            flatShading={true} />
        </mesh>
        : <NotIndicator position={[-1.6, 0.125, .5]} />}
    </group>
  )
}
OrGate.gate_name = OR_GATE
OrGate.delay = 1
OrGate.size_length = 1
OrGate.defaultInputs = [IN_A, IN_B]
OrGate.defaultOutputs = [OUT_Q]
OrGate.CheckPinType = (pin) => {
  if (pin === IN_A || pin === IN_B) return INPUT_PIN
  if (pin === OUT_Q) return OUTPUT_PIN
  return INVALID_PIN
}
OrGate.NextStep = (wireState = {}) => {
  return { [OUT_Q]: wireState[IN_A] || wireState[IN_B] }
}
OrGate.GetPinPositions = function (x, y, z) {
  return {
    in_A: [
      [x * 5 + 0.5, 0, z * 5 + 2],
      [x * 5 + 1, 0, z * 5 + 2],
    ],
    in_B: [
      [x * 5 + 0.5, y, z * 5 + 3],
      [x * 5 + 1, y, z * 5 + 3],
    ],
    out_Q: [
      [x * 5 + 4, y, z * 5 + 2.5],
      [x * 5 + 4.75, y, z * 5 + 2.5],
    ]
  }
}
OrGate.GetSelectPin = function (contactPoint, gateWorldPos, gatePos) {
  const pinPos = OrGate.GetPinPositions(gatePos.x, gatePos.y, gatePos.z)
  if (contactPoint.x > gateWorldPos.x) {
    return {
      pin: OUT_Q,
      position: pinPos[OUT_Q][1]
    }
  } else {
    if (contactPoint.z < gateWorldPos.z) {
      return {
        pin: IN_A,
        position: pinPos[IN_A][0]
      }
    } else {
      return {
        pin: IN_B,
        position: pinPos[IN_B][0]
      }
    }
  }
}
useGLTF.preload('/OR-transformed.glb')
