/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/AND.glb -o ./public/AndGate.jsx -T -E 
Files: ./models/AND.glb [21.62KB] > C:\Users\ducmi\vsc\aaaa\01_client\public\AND-transformed.glb [4.43KB] (80%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function AndGate(props) {
  const { nodes, materials } = useGLTF('/AND-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['1'].geometry} material={materials.Khoi} />
      <mesh geometry={nodes.Cot1.geometry} material={nodes.Cot1.material} />
    </group>
  )
}

useGLTF.preload('/AND-transformed.glb')
