/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/NXOR.glb -o ./public/NxorGate.jsx -T -E 
Files: ./models/NXOR.glb [35.14KB] > C:\Users\ducmi\vsc\aaaa\01_client\public\NXOR-transformed.glb [5.76KB] (84%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function NxorGate(props) {
  const { nodes, materials } = useGLTF('/NXOR-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['1'].geometry} material={materials.Khoi} />
      <mesh geometry={nodes.Cot1.geometry} material={nodes.Cot1.material} />
    </group>
  )
}

useGLTF.preload('/NXOR-transformed.glb')
