/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/OR.glb -o ./public/OrGate.jsx -T -E 
Files: ./models/OR.glb [11.28KB] > C:\Users\ducmi\vsc\aaaa\01_client\public\OR-transformed.glb [3.28KB] (71%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function OrGate(props) {
  const { nodes, materials } = useGLTF('/OR-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['3'].geometry} material={materials.Khoi} />
      <mesh geometry={nodes.Cot3.geometry} material={nodes.Cot3.material} />
    </group>
  )
}

useGLTF.preload('/OR-transformed.glb')
