/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/XOR.glb -o ./src/components/Canvas/Gates/XorGate.jsx -T -E 
Files: ./models/XOR.glb [7KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\XOR-transformed.glb [1.98KB] (72%)
*/

import { useGLTF } from '@react-three/drei'

import { GATE_COLORS, PORT_COLORS } from '@/utils/colors'
import { IN_A, IN_B, INPUT_PIN, INVALID_PIN, OUT_Q, OUTPUT_PIN, XOR_GATE } from '@/utils/constants'
import GateName from './GateName'

export default function XorGate({ name, ...props }) {
  const { nodes, materials } = useGLTF('/XOR-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <GateName name={name} />
      <mesh geometry={nodes['6'].geometry} material={materials.Khoi}>
        <meshStandardMaterial
          color={GATE_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
      <mesh position={[1.5, 0.125, 0]}>
        <boxGeometry args={[.4, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
      <mesh position={[-1.4, 0.125, .5]}>
        <boxGeometry args={[.5, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
      <mesh position={[-1.4, 0.125, -.5]}>
        <boxGeometry args={[.5, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true} />
      </mesh>
    </group>
  )
}
XorGate.gate_name = XOR_GATE
XorGate.delay = 4
XorGate.size_length = 1
XorGate.defaultInputs = JSON.stringify({
  [IN_A]: { srcGate: "", srcPin: "", selfGate: "", selfPin: "" },
  [IN_B]: { srcGate: "", srcPin: "", selfGate: "", selfPin: "" }
})
XorGate.defaultOutputs = JSON.stringify({
  [OUT_Q]: { status: false, destGate: [] }
})
XorGate.CheckPinType = (pin) => {
  if (pin === IN_A || pin === IN_B) return INPUT_PIN
  if (pin === OUT_Q) return OUTPUT_PIN
  return INVALID_PIN
}
XorGate.NextStep = (wireState = {}) => {
  return { [OUT_Q]: wireState[IN_A] != wireState[IN_B] }
}
XorGate.GetPinPositions = function (x, y, z) {
  return {
    in_A: [
      [x * 5 + 0.5, 0, z * 5 + 2],
      [x * 5 + 1, 0, z * 5 + 2],
    ],
    in_B: [
      [x * 5 + 0.5, y, z * 5 + 3],
      [x * 5 + 1, y, z * 5 + 3],
    ],
    out_Q: [
      [x * 5 + 4, y, z * 5 + 2.5],
      [x * 5 + 4.75, y, z * 5 + 2.5],
    ]
  }
}
XorGate.GetSelectPin = function (contactPoint, gateWorldPos, gatePos) {
  const pinPos = XorGate.GetPinPositions(gatePos.x, gatePos.y, gatePos.z)
  if (contactPoint.x > gateWorldPos.x) {
    return {
      pin: OUT_Q,
      position: pinPos[OUT_Q][1]
    }
  } else {
    if (contactPoint.z < gateWorldPos.z) {
      return {
        pin: IN_A,
        position: pinPos[IN_A][0]
      }
    } else {
      return {
        pin: IN_B,
        position: pinPos[IN_B][0]
      }
    }
  }
}
useGLTF.preload('/XOR-transformed.glb')
