/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./models/NOR.glb -o ./src/components/Canvas/Gates/NorGate.jsx -T -E 
Files: ./models/NOR.glb [28.94KB] > C:\Users\ducmi\projects\logic-gate-simulators\src\components\Canvas\Gates\NOR-transformed.glb [5.49KB] (81%)
*/

import { useGLTF } from '@react-three/drei'

import { GATE_COLORS, PORT_COLORS } from '@/utils/colors'
import { IN_A, IN_B, OUT_Q } from '@/utils/constants'

export default function NorGate(props) {
  const { nodes, materials } = useGLTF('/NOR-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['3'].geometry} material={materials.Khoi}>
        <meshStandardMaterial
          color={GATE_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
      <mesh geometry={nodes.Cot3.geometry} material={nodes.Cot3.material}>
        <meshStandardMaterial
          color={GATE_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
      <mesh position={[-1.3, 0.125, .5]}>
        <boxGeometry args={[.6, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
      <mesh position={[-1.3, 0.125, -.5]}>
        <boxGeometry args={[.6, .3, .3]} />
        <meshStandardMaterial
          color={PORT_COLORS}
          metalness={1}
          roughness={0.4}
          envMapIntensity={1.5}
          flatShading={true}
        />
      </mesh>
    </group>
  )
}

const gateState = { [IN_A]: 0, [IN_B]: 0, [OUT_Q]: 0 }
const wireState = { [IN_A]: 0, [IN_B]: 0, [OUT_Q]: 0 }
function NextState(wireState, gateState) {
  return {
    [IN_A]: wireState[IN_A],
    [IN_B]: wireState[IN_B],
    [OUT_Q]: !(wireState[IN_A] || wireState[IN_B])
  }
}

NorGate.inputs = [IN_A, IN_B]
NorGate.outputs = [OUT_Q]
NorGate.defaultState = { [IN_A]: false, [IN_B]: false, [OUT_Q]: false }
NorGate.NextState = NextState

useGLTF.preload('/NOR-transformed.glb')
